---
title: "EEZ MPAs"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

## db setup (once)

Add password (`S3cretP@asswordHERE!` not actual) into connection file `~/.pgpass` in specific format (`hostname:port:database:username:password`) for admin user:

```
# format of .pgpass: 
echo 'postgis:5432:gis:admin:S3cretP@asswordHERE!' > ~/.pgpass
chmod 0600 ~/.pgpass
```

## eez x mpas

```{r}
source("functions.R") # sets up db con

library(knitr)
```


Run sql query `eez_mpas.sql`:

```{r, eval=F}
# OLD SLOW: execute eez x mpas intersection
#system.time(
#  dbExecute(con, file2str("sql/eez_mpas.sql")))

path_sql <- here("sql/eez_mpas.sql")
path_log <- here("sql/eez_mpas.log")

cmd <- glue(
  "
  (printf '\n\n##### eez_mpas.sql #####\n'; echo `TZ='America/Los_Angeles' date`) >> '{{path_log}}'
  ( echo '\\timing on;'; cat '{{path_sql}}' }) | psql -U admin -h postgis -d gis -a >>{{path_log}} 2>&1 &", 
  .open = "{{", .close = "}}")
cat(cmd)
system(cmd)
```

Before fix:

|   cnt|geom_type             |
|-----:|:---------------------|
|     4|ST_MultiLineString    |
|     5|ST_GeometryCollection |
| 20662|ST_MultiPolygon       |

Now:

```{sql connection=con, output.var="eez_mpas_geomtypes"}
SELECT COUNT(eez_fid) AS cnt, ST_GeometryType(geom) AS geom_type
FROM eez_mpas GROUP BY ST_GeometryType(geom);
```

```{r}
kable(eez_mpas_geomtypes)
```


```{r}
eez_mpas <- st_read(con, query = "SELECT * FROM eez_mpas LIMIT 10;")
class(eez_mpas) # "sf" "data.frame" # only "data.frame" if using con as OdbcConnection
mapview::mapview(eez_mpas)

leaflet(eez_mpas) %>% 
  addProviderTiles(providers$Esri.OceanBasemap) %>% 
  addPolygons() %>% 
  addMiniMap()
```

## redo

```{sql connection=con, output.var="eez_rename_old"}
ALTER TABLE eez RENAME TO eez_old;
ALTER TABLE eez_mpas RENAME TO eez_mpas_old;
ALTER TABLE eez_mpa_notpoly RENAME TO eez_mpa_notpoly_old;
```


## debug sql processes

```bash
# check if still running query
ps -eaf | grep psql

# log into database
psql -U admin -h postgis -d gis
```

### kill process 

```sql
-- show not idle, all info
SELECT pid, query, * from pg_stat_activity WHERE state != 'idle' ORDER BY xact_start;

-- show not idle, just pid
SELECT pid from pg_stat_activity WHERE state != 'idle' ORDER BY xact_start;

-- show idle
SELECT pid, query from pg_stat_activity WHERE state = 'idle' ORDER BY xact_start;

-- kill by process id (pid)
SELECT pg_terminate_backend(7518);
```

```{r, eval=F}
# preview eez table in RStudio without geom field
flds_not_geo <- setdiff(dbListFields(con, "eez"), "geom")
eez <- dbGetQuery(
  con, glue(
    "SELECT {paste(flds_not_geo, collapse=',')} FROM eez"))
View(eez)
```
